#pragma once

#include <mlibc/sysdep-signatures.hpp>

namespace mlibc {

struct AurixSysdepsTags : LibcPanic,
                          LibcLog,
                          Isatty,
                          Write,
                          TcbSet,
                          AnonAllocate,
                          AnonFree,
                          Seek,
                          Exit,
                          Close,
                          FutexWake,
                          FutexWait,
                          Read,
                          Open,
                          OpenDir,
                          ReadEntries,
                          Stat,
                          VmMap,
                          VmUnmap,
                          VmProtect,
                          ClockGet,
                          Sleep,
                          GetUid,
                          GetEuid,
                          GetGid,
                          GetEgid,
                          GetPid,
                          GetPpid,
                          GetTid,
                          GetCwd,
                          Fork,
                          Chdir,
                          Waitpid,
                          Execve,
                          Mkdir,
                          Mkdirat,
                          Unlinkat,
                          Rmdir,
                          Rename,
                          Link,
                          Linkat,
                          Symlink,
                          Symlinkat,
                          Chmod,
                          Umask,
                          Kill,
                          Sigaction,
                          Fcntl,
                          Openat,
                          Readlink,
                          Poll,
                          Dup,
                          Dup2,
                          Pipe,
                          Ioctl,
                          Tcgetattr,
                          Tcsetattr,
                          Tcsendbreak,
                          Tcflow,
                          Tcflush,
                          Tcdrain,
                          Tcgetwinsize,
                          Tcsetwinsize {};

template <typename Tag>
using Sysdeps = SysdepOf<AurixSysdepsTags, Tag>;

} // namespace mlibc
